# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160104_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
