# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_person_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
    ]
